### ISSUE TITLE
Unable to Compile

### ISSUE THREAD

**Issue by Delkathus** [xenonsmurf/Servus-supported-version#1]
There are soo many code errors i can't even begin where to start.....

**Comment by xenonsmurf** [comment]
Sorry you are having issues compiling the source, I haven't actually tried to download it from here and compile. I just push updates from visual studios 2017.  Once my laptop has finished with this stupid update I will download it and see what's up.

**Comment by xenonsmurf** [comment]
i downloaded it and it compiled fine. maybe check if all the required .dlls are referenced.

**Comment by Delkathus** [comment]
i think the one dll i had was not downloaded properly, redownloaded it and worked fine. lol

**Comment by xenonsmurf** [comment]
Great, glad you got it working Delkathus.
